---
# SPDX-FileCopyrightText: 2024 The Malware as a Service development team
#
# SPDX-License-Identifier: CC0-1.0
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
