---
# SPDX-FileCopyrightText: 2023 The MalwareTracesGenerator development team
#
# SPDX-License-Identifier: CC0-1.0
name: Lint the project
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  reuse:
    name: Lint with REUSE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint licenses
        uses: fsfe/reuse-action@v3
  markdownlint-cli2:
    name: Lint with markdownlint-cli2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint Markdown code
        uses: DavidAnson/markdownlint-cli2-action@v17
