---
# SPDX-FileCopyrightText: 2024 The .github development team
# yamllint disable-line
# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0
name: Lint the project
on: [push, pull_request]
jobs:
  yamllint:
    name: Lint with yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create requirements file for setup-python
        run: touch ./requirements.txt
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip
      - name: Install yamllint
        run: pip install yamllint
      - name: Check YAML formatting
        run: yamllint -s .
  reuse:
    name: Lint with REUSE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint licenses
        uses: fsfe/reuse-action@v3
  markdownlint-cli2:
    name: Lint with markdownlint-cli2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint Markdown code
        uses: DavidAnson/markdownlint-cli2-action@v17
